MusicStore/MusicStore/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelos;
using BusinessLogic;

namespace MusicStore.Controllers
{
    public class CarritoController : Controller
    {
        CarritoBLL carrito = new CarritoBLL();

        public ActionResult Index()
        {          
            return View(carrito.getCarrito());
        }

        public ActionResult AgregarCarrito(int Id)
        {    
            carrito.AgregarProducto(Id);            
            return RedirectToAction("Index");            
        }
        public ActionResult RemoverDeCarrito(int Id)
        {
            carrito.Eliminar(Id);
            return RedirectToAction("Index");
        }
       
    }
}

MusicStore/MusicStore/Controllers/MusicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelos;
using BusinessLogic;

namespace MusicStore.Controllers
{
    public class MusicaController : Controller
    {
        // GET: Musica
        public ActionResult Index()
        {
            MusicaBLL info = new MusicaBLL();
            return View(info.getCanciones());
        }
    }
}

MusicStore/MusicStore/Views/Musica/Index.cshtml
@model List<Modelos.Musica>
@{
    ViewBag.Title = "Música";
}

<h2>Música</h2>
<table class="table">
    <tr>

        <th>
            @Html.Label("Id")
            @*@Ajax.ActionLink("Song", "Alfabetico", "Musica", new AjaxOptions { UpdateTargetId = "result", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" })*@
        </th>
        <th>
            @Html.Label("Canción")
            @*@Ajax.ActionLink("Artist", "Alfabetico", "Musica", new AjaxOptions { UpdateTargetId = "result", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" })*@
        </th>
        <th>
            @Html.Label("Artista")
        </th>
        <th>
            @Html.Label("Género")
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>
                @Html.DisplayFor(modelItem => item.Id)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.Nombre)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.Autor.Nombre)
            </th>
            <th>
                @Html.DisplayFor(modelItem => item.Genero.Nombre)
            </th>
            <th>
                @Html.ActionLink("Agregar a Carrito", "AgregarCarrito", "Carrito",
                new { id = item.Id }, "")
            </th>
        </tr>
    }
</table>