MusicStore/MusicStore/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelos;
using BusinessLogic;

namespace MusicStore.Controllers
{
    public class CarritoController : Controller
    {
        CarritoBLL carrito = new CarritoBLL();

        public ActionResult Index()
        {          
            return View(carrito.getCarrito());
        }

        public ActionResult AgregarCarrito(int Id)
        {    
            carrito.AgregarProducto(Id);            
            return RedirectToAction("Index");            
        }
        public ActionResult RemoverDeCarrito(int Id)
        {
            carrito.Eliminar(Id);
            return RedirectToAction("Index");
        }
       
    }
}

MusicStore/MusicStore/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelos;
using BusinessLogic;

namespace MusicStore.Controllers
{
    public class PagoController : Controller
    {
        // GET: Pago
        public ActionResult Index()
        {
            PagoBLL pago = new PagoBLL();

            return View(pago.getPagos());
        }
        public ActionResult Pago()
        {
            Random r = new Random();
            PagoBLL pago = new PagoBLL();
            CarritoBLL carrito = new CarritoBLL();

            pago.Agregar(r.Next(1000, 9999), DateTime.Today, carrito.getCarrito());
            carrito.EliminarTodo();
            return RedirectToAction("Index");
        }
    }
}

MusicStore/MusicStore/Views/Carrito/Index.cshtml
@model IEnumerable<Modelos.Musica>

@{
    ViewBag.Title = "Carrito";
}

<h2>Carrito</h2>

<p>
    @if (Model.Count() > 0)
    {
        @Html.ActionLink("Efectuar Pago", "Pago", "Pago");    
    }
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.ActionLink("Remover de Carrito", "RemoverDeCarrito", new { id = item.Id })
            </td>
        </tr>
    }

    <tr>
        <th>
            Subtotal
        </th>
        <th>
            @Model.Sum(x => x.Precio)
        </th>
        <th></th>
    </tr>

</table>